unit 2 / lesson 4 / project 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn import preprocessing

In [2]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls')

In [3]:
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NEW YORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.drop([0, 1, 2], axis=0, inplace = True)

In [5]:
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns = df.iloc[0]

In [7]:
df

3,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.drop([3], axis=0, inplace = True)

In [9]:
df

3,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.reset_index(drop=True)

In [11]:
df

3,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
0,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
1,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
2,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
3,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
4,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
5,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
6,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
7,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
8,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
9,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
10,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
11,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
12,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
13,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
14,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
15,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
16,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
17,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
18,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
19,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
20,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
21,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
22,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
23,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
24,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
25,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
26,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
27,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
28,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
29,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
322,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
323,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
324,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
325,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
326,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
327,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
328,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
329,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
330,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
331,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
332,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
333,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
334,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
335,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
336,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
337,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
338,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
339,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
340,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
341,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
342,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
343,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
344,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
345,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
346,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
347,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
348,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.drop([348, 349, 350], axis=0, inplace = True)

In [13]:
df.rename(columns={ df.columns[0]: "city" }, inplace=True)
df.rename(columns={ df.columns[1]: "population" }, inplace=True)
df.rename(columns={ df.columns[2]: "violent_crime" }, inplace=True)
df.rename(columns={ df.columns[3]: "murder_nonnegligent_manslaughter" }, inplace=True)
df.rename(columns={ df.columns[4]: "rape_rev1" }, inplace=True)
df.rename(columns={ df.columns[5]: "rape_legacy" }, inplace=True)
df.rename(columns={ df.columns[6]: "robbery" }, inplace=True)
df.rename(columns={ df.columns[7]: "aggravated_assult" }, inplace=True)
df.rename(columns={ df.columns[8]: "property_crime" }, inplace=True)
df.rename(columns={ df.columns[9]: "burglary" }, inplace=True)
df.rename(columns={ df.columns[10]: "larceny_theft" }, inplace=True)
df.rename(columns={ df.columns[11]: "motor_vehicle_theft" }, inplace=True)
df.rename(columns={ df.columns[12]: "arson3" }, inplace=True)

In [14]:
df

3,city,population,violent_crime,murder_nonnegligent_manslaughter,rape_rev1,rape_legacy,robbery,aggravated_assult,property_crime,burglary,larceny_theft,motor_vehicle_theft,arson3
0,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
1,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
2,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
3,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
4,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
5,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
6,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
7,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
8,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
9,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
10,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
11,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
12,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
13,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
14,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
15,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
16,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
17,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
18,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
19,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
20,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
21,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
22,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
23,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
24,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
25,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
26,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
27,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
28,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
29,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,Tupper Lake Village,3642,3,0,NaN,0,0,3,83,22,59,2,NaN
319,Tuxedo Park Village,615,0,0,NaN,0,0,0,0,0,0,0,0
320,Ulster Town,12195,14,0,NaN,3,2,9,437,25,410,2,NaN
321,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
322,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
323,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
324,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
325,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
326,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
327,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
328,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
329,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
330,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
331,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
332,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
333,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
334,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
335,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
336,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
337,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
338,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
339,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
340,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
341,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
342,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
343,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
344,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
345,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
346,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
347,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348 entries, 0 to 347
Data columns (total 13 columns):
city                                348 non-null object
population                          348 non-null object
violent_crime                       348 non-null object
murder_nonnegligent_manslaughter    348 non-null object
rape_rev1                           0 non-null object
rape_legacy                         348 non-null object
robbery                             348 non-null object
aggravated_assult                   348 non-null object
property_crime                      348 non-null object
burglary                            348 non-null object
larceny_theft                       348 non-null object
motor_vehicle_theft                 348 non-null object
arson3                              187 non-null object
dtypes: object(13)
memory usage: 38.1+ KB

In [17]:
df.drop(['rape_rev1'], axis=1, inplace = True)

In [23]:
df = df.fillna(0)

In [24]:
df['population'] = df['population'].astype('Int64')
df['violent_crime'] = df['violent_crime'].astype('Int64')
df['murder_nonnegligent_manslaughter'] = df['murder_nonnegligent_manslaughter'].astype('Int64')
df['rape_legacy'] = df['rape_legacy'].astype('Int64')
df['robbery'] = df['robbery'].astype('Int64')
df['aggravated_assult'] = df['aggravated_assult'].astype('Int64')
df['property_crime'] = df['property_crime'].astype('Int64')
df['burglary'] = df['burglary'].astype('Int64')
df['larceny_theft'] = df['larceny_theft'].astype('Int64')
df['motor_vehicle_theft'] = df['motor_vehicle_theft'].astype('Int64')
df['arson3'] = df['arson3'].astype('Int64')

In [25]:
df['pop_sqrt'] = np.sqrt(df['population'])

In [26]:
df

3,city,population,violent_crime,murder_nonnegligent_manslaughter,rape_legacy,robbery,aggravated_assult,property_crime,burglary,larceny_theft,motor_vehicle_theft,arson3,pop_sqrt
0,Adams Village,1861,0,0,0,0,0,12,2,10,0,0,43.139309
1,Addison Town and Village,2577,3,0,0,0,3,24,3,20,1,0,50.764161
2,Akron Village,2846,3,0,0,0,3,16,1,15,0,0,53.347915
3,Albany,97956,791,8,30,227,526,4090,705,3243,142,0,312.979233
4,Albion Village,6388,23,0,3,4,16,223,53,165,5,0,79.924965
5,Alfred Village,4089,5,0,0,3,2,46,10,36,0,0,63.945289
6,Allegany Village,1781,3,0,0,0,3,10,0,10,0,0,42.201896
7,Amherst Town,118296,107,1,7,31,68,2118,204,1882,32,3,343.941856
8,Amityville Village,9519,9,0,2,4,3,210,16,188,6,1,97.565363
9,Amsterdam,18182,30,0,0,12,18,405,99,291,15,0,134.840647
10,Arcade Village,2053,0,0,0,0,0,39,3,35,1,0,45.310043
11,Ardsley Village,4523,5,0,0,3,2,33,4,28,1,0,67.253253
12,Asharoken Village,658,0,0,0,0,0,2,0,2,0,0,25.651511
13,Attica Village,2522,2,0,0,0,2,5,0,4,1,0,50.219518
14,Auburn,27270,96,1,20,22,53,859,132,721,6,0,165.136307
15,Avon Village,3333,1,0,0,1,0,25,3,20,2,0,57.732140
16,Baldwinsville Village,7473,5,0,0,1,4,88,10,77,1,0,86.446515
17,Ballston Spa Village,5418,8,0,0,3,5,94,16,78,0,1,73.607065
18,Batavia,15374,57,0,7,13,37,559,103,454,2,0,123.991935
19,Bath Village,5733,15,0,1,3,11,191,32,157,2,2,75.716577
20,Bedford Town,17627,5,0,0,1,4,156,26,127,3,0,132.766713
21,Bethlehem Town,34243,13,0,0,3,10,442,50,388,4,0,185.048642
22,Binghamton,46304,284,3,19,101,161,2349,525,1767,57,0,215.183643
23,Black River,1410,0,0,0,0,0,14,2,12,0,0,37.549967
24,Blooming Grove Town,12001,8,0,1,0,7,99,20,72,7,0,109.549076
25,Bolivar Village,1022,1,0,0,0,1,4,2,2,0,0,31.968735
26,Bolton Town,2325,2,0,0,0,2,24,4,20,0,0,48.218254
27,Boonville Village,2054,1,0,0,0,1,20,6,14,0,0,45.321077
28,Brant Town,2065,4,0,0,1,3,31,9,20,2,0,45.442271
29,Brewster,2358,0,0,0,0,0,13,3,10,0,0,48.559242
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,Tupper Lake Village,3642,3,0,0,0,3,83,22,59,2,0,60.348985
319,Tuxedo Park Village,615,0,0,0,0,0,0,0,0,0,0,24.799194
320,Ulster Town,12195,14,0,3,2,9,437,25,410,2,0,110.430974
321,Utica,61686,361,7,27,102,225,2528,449,1997,82,0,248.366664
322,Vestal Town,27980,16,0,2,6,8,571,39,523,9,0,167.272233
323,Walden Village,6887,18,1,2,1,14,142,13,124,5,0,82.987951
324,Wallkill Town,27940,40,0,3,16,21,767,91,650,26,1,167.152625
325,Walton Village,3012,6,0,1,0,5,68,18,50,0,0,54.881691
326,Warsaw Village,3453,6,0,1,0,5,78,5,73,0,0,58.762233
327,Washingtonville Village,5828,2,0,0,1,1,58,5,51,2,0,76.341339
328,Waterford Town and Village,8392,4,0,0,0,4,59,6,52,1,0,91.607860
329,Waterloo Village,5175,11,0,0,3,8,194,23,169,2,0,71.937473
330,Watertown,28179,109,0,12,16,81,1165,169,953,43,0,167.866018
331,Watervliet,10245,26,1,3,11,11,242,58,163,21,0,101.217587
332,Watkins Glen Village,1862,6,0,0,0,6,92,10,80,2,0,43.150898
333,Waverly Village,4337,5,0,0,1,4,54,9,41,4,0,65.855903
334,Webster Town and Village,43777,21,0,2,3,16,469,101,361,7,0,209.229539
335,Weedsport Village,1797,0,0,0,0,0,25,5,20,0,0,42.391037
336,Wellsville Village,4574,11,0,1,0,10,164,32,129,3,1,67.631354
337,Westhampton Beach Village,1732,2,0,0,0,2,44,4,37,3,0,41.617304
338,West Seneca Town,44821,35,1,1,9,24,896,166,710,20,0,211.709707
339,Whitehall Village,2604,6,0,0,0,6,62,12,49,1,0,51.029403
340,White Plains,57559,78,1,3,28,46,1232,77,1134,21,0,239.914568
341,Whitesboro Village,3733,4,0,0,0,4,36,14,21,1,0,61.098281
342,Whitestown Town,9141,0,0,0,0,0,77,13,61,3,0,95.608577
343,Woodbury Town,10685,3,0,0,2,1,541,9,529,3,0,103.368274
344,Woodridge Village,829,7,0,0,0,7,17,8,9,0,0,28.792360
345,Woodstock Town,5931,2,0,0,0,2,58,13,45,0,0,77.012986
346,Yonkers,199134,1036,6,25,390,615,2368,470,1662,236,10,446.244328
347,Yorktown Town,36643,15,0,0,2,13,334,45,287,2,0,191.423614

In [37]:
df['murder_bool'] = 0
df['robbery_bool'] = 0

for index, row in df.iterrows():
    if row['murder_nonnegligent_manslaughter'] > 0:
        df.loc[index, 'murder_bool'] = 1

for index, row in df.iterrows():
    if row['robbery'] > 0:
        df.loc[index, 'robbery_bool'] = 1

In [38]:
df

3,city,population,violent_crime,murder_nonnegligent_manslaughter,rape_legacy,robbery,aggravated_assult,property_crime,burglary,larceny_theft,motor_vehicle_theft,arson3,pop_sqrt,murder_bool,robbery_bool
0,Adams Village,1861,0,0,0,0,0,12,2,10,0,0,43.139309,0,0
1,Addison Town and Village,2577,3,0,0,0,3,24,3,20,1,0,50.764161,0,0
2,Akron Village,2846,3,0,0,0,3,16,1,15,0,0,53.347915,0,0
3,Albany,97956,791,8,30,227,526,4090,705,3243,142,0,312.979233,1,1
4,Albion Village,6388,23,0,3,4,16,223,53,165,5,0,79.924965,0,1
5,Alfred Village,4089,5,0,0,3,2,46,10,36,0,0,63.945289,0,1
6,Allegany Village,1781,3,0,0,0,3,10,0,10,0,0,42.201896,0,0
7,Amherst Town,118296,107,1,7,31,68,2118,204,1882,32,3,343.941856,1,1
8,Amityville Village,9519,9,0,2,4,3,210,16,188,6,1,97.565363,0,1
9,Amsterdam,18182,30,0,0,12,18,405,99,291,15,0,134.840647,0,1
10,Arcade Village,2053,0,0,0,0,0,39,3,35,1,0,45.310043,0,0
11,Ardsley Village,4523,5,0,0,3,2,33,4,28,1,0,67.253253,0,1
12,Asharoken Village,658,0,0,0,0,0,2,0,2,0,0,25.651511,0,0
13,Attica Village,2522,2,0,0,0,2,5,0,4,1,0,50.219518,0,0
14,Auburn,27270,96,1,20,22,53,859,132,721,6,0,165.136307,1,1
15,Avon Village,3333,1,0,0,1,0,25,3,20,2,0,57.732140,0,1
16,Baldwinsville Village,7473,5,0,0,1,4,88,10,77,1,0,86.446515,0,1
17,Ballston Spa Village,5418,8,0,0,3,5,94,16,78,0,1,73.607065,0,1
18,Batavia,15374,57,0,7,13,37,559,103,454,2,0,123.991935,0,1
19,Bath Village,5733,15,0,1,3,11,191,32,157,2,2,75.716577,0,1
20,Bedford Town,17627,5,0,0,1,4,156,26,127,3,0,132.766713,0,1
21,Bethlehem Town,34243,13,0,0,3,10,442,50,388,4,0,185.048642,0,1
22,Binghamton,46304,284,3,19,101,161,2349,525,1767,57,0,215.183643,1,1
23,Black River,1410,0,0,0,0,0,14,2,12,0,0,37.549967,0,0
24,Blooming Grove Town,12001,8,0,1,0,7,99,20,72,7,0,109.549076,0,0
25,Bolivar Village,1022,1,0,0,0,1,4,2,2,0,0,31.968735,0,0
26,Bolton Town,2325,2,0,0,0,2,24,4,20,0,0,48.218254,0,0
27,Boonville Village,2054,1,0,0,0,1,20,6,14,0,0,45.321077,0,0
28,Brant Town,2065,4,0,0,1,3,31,9,20,2,0,45.442271,0,1
29,Brewster,2358,0,0,0,0,0,13,3,10,0,0,48.559242,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,Tupper Lake Village,3642,3,0,0,0,3,83,22,59,2,0,60.348985,0,0
319,Tuxedo Park Village,615,0,0,0,0,0,0,0,0,0,0,24.799194,0,0
320,Ulster Town,12195,14,0,3,2,9,437,25,410,2,0,110.430974,0,1
321,Utica,61686,361,7,27,102,225,2528,449,1997,82,0,248.366664,1,1
322,Vestal Town,27980,16,0,2,6,8,571,39,523,9,0,167.272233,0,1
323,Walden Village,6887,18,1,2,1,14,142,13,124,5,0,82.987951,1,1
324,Wallkill Town,27940,40,0,3,16,21,767,91,650,26,1,167.152625,0,1
325,Walton Village,3012,6,0,1,0,5,68,18,50,0,0,54.881691,0,0
326,Warsaw Village,3453,6,0,1,0,5,78,5,73,0,0,58.762233,0,0
327,Washingtonville Village,5828,2,0,0,1,1,58,5,51,2,0,76.341339,0,1
328,Waterford Town and Village,8392,4,0,0,0,4,59,6,52,1,0,91.607860,0,0
329,Waterloo Village,5175,11,0,0,3,8,194,23,169,2,0,71.937473,0,1
330,Watertown,28179,109,0,12,16,81,1165,169,953,43,0,167.866018,0,1
331,Watervliet,10245,26,1,3,11,11,242,58,163,21,0,101.217587,1,1
332,Watkins Glen Village,1862,6,0,0,0,6,92,10,80,2,0,43.150898,0,0
333,Waverly Village,4337,5,0,0,1,4,54,9,41,4,0,65.855903,0,1
334,Webster Town and Village,43777,21,0,2,3,16,469,101,361,7,0,209.229539,0,1
335,Weedsport Village,1797,0,0,0,0,0,25,5,20,0,0,42.391037,0,0
336,Wellsville Village,4574,11,0,1,0,10,164,32,129,3,1,67.631354,0,0
337,Westhampton Beach Village,1732,2,0,0,0,2,44,4,37,3,0,41.617304,0,0
338,West Seneca Town,44821,35,1,1,9,24,896,166,710,20,0,211.709707,1,1
339,Whitehall Village,2604,6,0,0,0,6,62,12,49,1,0,51.029403,0,0
340,White Plains,57559,78,1,3,28,46,1232,77,1134,21,0,239.914568,1,1
341,Whitesboro Village,3733,4,0,0,0,4,36,14,21,1,0,61.098281,0,0
342,Whitestown Town,9141,0,0,0,0,0,77,13,61,3,0,95.608577,0,0
343,Woodbury Town,10685,3,0,0,2,1,541,9,529,3,0,103.368274,0,1
344,Woodridge Village,829,7,0,0,0,7,17,8,9,0,0,28.792360,0,0
345,Woodstock Town,5931,2,0,0,0,2,58,13,45,0,0,77.012986,0,0
346,Yonkers,199134,1036,6,25,390,615,2368,470,1662,236,10,446.244328,1,1
347,Yorktown Town,36643,15,0,0,2,13,334,45,287,2,0,191.423614,0,1